[package]
name = "dev-new"
version = "0.1.0"
authors = ["bag"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
dialoguer = "0.6.2"
clipboard = "0.5.0"
toml = "0.5.6"
dirs = "3.0.1"
duct = "0.13.4"